all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

prod:
  hosts:
    client1:
      ansible_host: 10.0.2.4
      name: ENSUP
      html_title: Ensup Student
      port: 8080
      project_name: webapp
      docker_image_name: webapp
